### ISSUE TITLE
[BUG] Loop in documentation links.

### ISSUE THREAD

**Issue by spikespaz** [luxonauta/luxacss#48]
# 1. Look for link to docs
![image](https://github.com/luxonauta/luxacss/assets/12502988/c1e3162b-a19b-4efc-bd10-f735ae57b4fe)
# 2. Click it
![image](https://github.com/luxonauta/luxacss/assets/12502988/7eac9f22-d586-4264-a4af-dd60e298177a)
# 3. This isn't the docs, but there's a button
![image](https://github.com/luxonauta/luxacss/assets/12502988/f52c591b-efeb-472a-bfa2-b404fc04c184)
# 4. Click it
![image](https://github.com/luxonauta/luxacss/assets/12502988/c617466f-91fa-4b7b-9dc1-388b826d12d3)
# 5. Hmmmm
![image](https://github.com/luxonauta/luxacss/assets/12502988/08424bfc-f7e2-47d3-8632-9aee06298655)

**Comment by luxonauta** [comment]
Thanks for pointing this out. I'm updating the documentation, hence the current format. I appreciate your patience and will update you soon. Just pushed a simplified build version. 🌱😊

**Comment by luxonauta** [comment]
@spikespaz, thanks for your patience; the docs are live. I'll keep working on them, tho! ✨

- https://www.luxacss.com/
