### ISSUE TITLE
[BUG] Dracula

### ISSUE THREAD

**Issue by Pakrohk** [luxonauta/luxacss#59]
This is not a bug, not even about this project, but I couldn't find a better place to post it.
Bro, I think you forgot about the Dracula project a long time ago.
https://github.com/dracula/qtile/pull/2
Please confirm this request.

**Comment by luxonauta** [comment]
Hey Pakrohk, the ideal would be to post it in the repo itself. You can tag me 😊. In fact, we have several plans and things we are doing in the background. As for this specific PR, I approved it!
